import os
import csv
import io
import json
import smtplib
import ssl
import threading
import time
from datetime import datetime, timedelta, timezone
from email.message import EmailMessage
from email.utils import formataddr
from zoneinfo import ZoneInfo
from functools import wraps
from flask import (
    Flask, render_template, redirect, url_for, 
    request, session, flash, jsonify, send_from_directory, abort
)
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.exc import IntegrityError
from authlib.integrations.flask_client import OAuth
from werkzeug.utils import secure_filename
from werkzeug.middleware.proxy_fix import ProxyFix
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# Configure ProxyFix to process reverse proxy headers from Cloudflare Tunnel
# x_for=1, x_proto=1, x_host=1, x_port=1, x_prefix=1
app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_port=1, x_prefix=1)

# Ensure external URLs generated by url_for default to HTTPS
app.config['PREFERRED_URL_SCHEME'] = 'https'

app.secret_key = os.getenv("SECRET_KEY", "default-dev-key-change-in-production")
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///robotics_attendance.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# Protected upload directory (Outside public static path)
app.config['UPLOAD_FOLDER'] = os.path.join(app.root_path, 'uploads', 'photos')
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024

os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)

db = SQLAlchemy(app)
oauth = OAuth(app)

google = oauth.register(
    name='google',
    client_id=os.getenv("GOOGLE_CLIENT_ID"),
    client_secret=os.getenv("GOOGLE_CLIENT_SECRET"),
    server_metadata_url='https://accounts.google.com/.well-known/openid-configuration',
    client_kwargs={'scope': 'openid email profile'},
)

# ==========================================
# TIMEZONE & CUTOFF CONFIGURATION
# ==========================================
LOCAL_TZ = ZoneInfo("America/Edmonton")  # Mountain Time (MST/MDT)
ABSENCE_CUTOFF_HOURS = 5                  # Absences locked 5 hours before session start
EARLY_CHECKIN_BUFFER_MINUTES = 10         # Students may sign in this many minutes early if a mentor/admin is already in

def get_local_now():
    """Returns current date and time in naive Mountain Time."""
    return datetime.now(ZoneInfo("UTC")).astimezone(LOCAL_TZ).replace(tzinfo=None)

def to_local_naive(dt):
    """Ensures input timestamps are converted to naive Mountain Time objects."""
    if dt is None:
        return None
    if dt.tzinfo is not None:
        return dt.astimezone(LOCAL_TZ).replace(tzinfo=None)
    return dt

# ==========================================
# DATABASE MODELS
# ==========================================

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    name = db.Column(db.String(100), nullable=True)
    barcode = db.Column(db.String(50), unique=True, nullable=True)
    role = db.Column(db.String(20), default='student')
    photo_url = db.Column(db.String(255), nullable=True)

    absences = db.relationship('AbsenceNotice', backref='user', lazy=True)
    logs = db.relationship('AttendanceLog', backref='user', lazy=True)

    @property
    def is_mentor_or_admin(self):
        return self.role in ['mentor', 'admin']

class BuildSession(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    location = db.Column(db.String(100), nullable=False)
    start_time = db.Column(db.DateTime, nullable=False)
    end_time = db.Column(db.DateTime, nullable=False)
    created_by = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)

    absences = db.relationship('AbsenceNotice', backref='session', lazy=True)
    logs = db.relationship('AttendanceLog', backref='session', lazy=True)

class AbsenceNotice(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    session_id = db.Column(db.Integer, db.ForeignKey('build_session.id'), nullable=False)
    start_time = db.Column(db.DateTime, nullable=False)
    end_time = db.Column(db.DateTime, nullable=False)
    reason = db.Column(db.String(255), nullable=True)

class AttendanceLog(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    # Nullable so manual hour adjustments (not tied to a real build session) can be recorded.
    session_id = db.Column(db.Integer, db.ForeignKey('build_session.id'), nullable=True)
    check_in = db.Column(db.DateTime, default=get_local_now)
    check_out = db.Column(db.DateTime, nullable=True)
    # Free-text note, used mainly for manual hour adjustments made by a mentor/admin.
    note = db.Column(db.String(255), nullable=True)
    # True when this row was created via the manual "adjust hours" tool rather than an
    # actual check-in/check-out event.
    is_manual = db.Column(db.Boolean, default=False, nullable=False)

    @property
    def duration_hours(self):
        if self.check_in and self.check_out:
            delta = self.check_out - self.check_in
            return round(delta.total_seconds() / 3600.0, 2)
        return 0.0

    @property
    def check_in_fmt(self):
        """Formatted string for arrival time in Mountain Time."""
        if self.check_in:
            return self.check_in.strftime('%Y-%m-%d %I:%M %p MST')
        return "N/A"

    @property
    def check_out_fmt(self):
        """Formatted string for departure time in Mountain Time."""
        if self.check_out:
            return self.check_out.strftime('%Y-%m-%d %I:%M %p MST')
        return "Still Active"

class SessionReminder(db.Model):
    """One row per build session whose mentor absence-reminder has been handled.
    The unique constraint on session_id is what stops the reminder from ever
    being sent twice (even across restarts or multiple worker processes)."""
    id = db.Column(db.Integer, primary_key=True)
    session_id = db.Column(db.Integer, db.ForeignKey('build_session.id'), unique=True, nullable=False)
    sent_at = db.Column(db.DateTime, default=get_local_now)

# ==========================================
# HELPERS & DECORATORS
# ==========================================

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user_id' not in session:
            flash("Please log in to access this page.", "warning")
            return redirect(url_for('login'))
        return f(*args, **kwargs)
    return decorated_function

def role_required(*roles):
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            if 'user_id' not in session:
                flash("Please log in first.", "warning")
                return redirect(url_for('login'))
            current_user = User.query.get(session['user_id'])
            if not current_user or current_user.role not in roles:
                flash("Unauthorized action for your role level.", "danger")
                return redirect(url_for('dashboard'))
            return f(*args, **kwargs)
        return decorated_function
    return decorator

# ==========================================
# MENTOR ABSENCE REMINDER EMAILS (SMTP)
# ==========================================
# All configured through .env — see .env.example.

SMTP_HOST = os.getenv("SMTP_HOST", "").strip()
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "").strip()
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
SMTP_SECURITY = os.getenv("SMTP_SECURITY", "starttls").strip().lower()   # starttls | ssl | none
SMTP_FROM_NAME = os.getenv("SMTP_FROM_NAME", "").strip()                 # custom sender name
SMTP_FROM_EMAIL = os.getenv("SMTP_FROM_EMAIL", "").strip() or SMTP_USER

# Public URL of the portal, used in the student invitation email
APP_URL = os.getenv("APP_URL", "https://attendance.albt.qzz.io/").strip()

REMINDER_HOURS_BEFORE = float(os.getenv("REMINDER_HOURS_BEFORE", "6"))
REMINDER_SEND_IF_NO_ABSENCES = os.getenv("REMINDER_SEND_IF_NO_ABSENCES", "false").strip().lower() in ("1", "true", "yes")
REMINDER_CHECK_INTERVAL_SECONDS = 60


def smtp_configured():
    return bool(SMTP_HOST and SMTP_USER and SMTP_PASSWORD and SMTP_FROM_EMAIL)


def _open_smtp():
    """Open and authenticate an SMTP connection using the .env settings."""
    if SMTP_SECURITY == "ssl":
        server = smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT, context=ssl.create_default_context(), timeout=30)
    else:
        server = smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30)
        if SMTP_SECURITY == "starttls":
            server.starttls(context=ssl.create_default_context())
    server.login(SMTP_USER, SMTP_PASSWORD)
    return server


def _make_message(to_email, subject, body):
    msg = EmailMessage()
    msg["From"] = formataddr((SMTP_FROM_NAME, SMTP_FROM_EMAIL)) if SMTP_FROM_NAME else SMTP_FROM_EMAIL
    msg["To"] = to_email
    msg["Subject"] = subject
    msg.set_content(body)
    return msg


def send_emails(messages):
    """Send a list of EmailMessage objects over one connection.
    Returns how many were sent successfully; a failure on one doesn't stop the rest."""
    if not messages:
        return 0
    sent = 0
    server = _open_smtp()
    try:
        for msg in messages:
            try:
                server.send_message(msg)
                sent += 1
            except Exception:
                app.logger.exception("Failed to send email to %s", msg["To"])
    finally:
        try:
            server.quit()
        except Exception:
            pass
    return sent


def _fmt_date(dt):
    return f"{dt:%A, %B} {dt.day}, {dt.year}"


def _fmt_time(dt):
    return dt.strftime("%I:%M %p").lstrip("0")


def _collect_absentees(build_session):
    """Return a sorted list of 'Name' / 'Name (6:30 PM to 8:00 PM)' strings for everyone
    who reported an absence for this session. Partial-session absences show their window."""
    s_start = to_local_naive(build_session.start_time)
    s_end = to_local_naive(build_session.end_time)
    by_user = {}
    for notice in AbsenceNotice.query.filter_by(session_id=build_session.id).all():
        by_user.setdefault(notice.user_id, []).append(notice)

    entries = []
    for notices in by_user.values():
        user = notices[0].user
        name = user.name or user.email
        covers_all = any(
            to_local_naive(n.start_time) <= s_start and to_local_naive(n.end_time) >= s_end
            for n in notices
        )
        if covers_all:
            entries.append(name)
        else:
            windows = ", ".join(
                f"{_fmt_time(to_local_naive(n.start_time))} to {_fmt_time(to_local_naive(n.end_time))}"
                for n in sorted(notices, key=lambda n: n.start_time)
            )
            entries.append(f"{name} ({windows})")
    return sorted(entries, key=str.lower)


def _reminder_body(mentor_name, build_session, absentees):
    s_start = to_local_naive(build_session.start_time)
    s_end = to_local_naive(build_session.end_time)
    when = f"for the session on {_fmt_date(s_start)} from {_fmt_time(s_start)} to {_fmt_time(s_end)}"

    if not absentees:
        return f"Hey {mentor_name},\n\n{when[0].upper() + when[1:]}, nobody reported they would be absent.\n"
    if len(absentees) == 1:
        return f"Hey {mentor_name},\n\n{when[0].upper() + when[1:]}, {absentees[0]} reported they would be absent.\n"

    lines = "\n".join(f"- {a}" for a in absentees)
    return (
        f"Hey {mentor_name},\n\n"
        f"{when[0].upper() + when[1:]}, the following people reported they would be absent:\n\n"
        f"{lines}\n"
    )


def _invite_body(student_name, student_email):
    return (
        f"Hey {student_name},\n\n"
        f"We now have an attendance system for build sessions. You can use it to report "
        f"when you'll be absent from a session.\n\n"
        f"Sign in with the Google account for {student_email} here:\n"
        f"{APP_URL}\n\n"
        f"Absences need to be reported at least {ABSENCE_CUTOFF_HOURS} hours before a session starts.\n"
    )


def process_session_reminders():
    """Find sessions starting within REMINDER_HOURS_BEFORE that haven't had their
    reminder handled yet, and email every mentor/admin the absence list."""
    now = get_local_now()
    horizon = now + timedelta(hours=REMINDER_HOURS_BEFORE)

    due_sessions = BuildSession.query.filter(
        BuildSession.start_time > now,
        BuildSession.start_time <= horizon
    ).order_by(BuildSession.start_time.asc()).all()

    for build_session in due_sessions:
        if SessionReminder.query.filter_by(session_id=build_session.id).first():
            continue

        # Claim this session first. If another process beat us to it, the unique
        # constraint raises IntegrityError and we skip — so no duplicate emails.
        try:
            claim = SessionReminder(session_id=build_session.id, sent_at=now)
            db.session.add(claim)
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
            continue

        absentees = _collect_absentees(build_session)
        if not absentees and not REMINDER_SEND_IF_NO_ABSENCES:
            continue  # nothing to report; leave the claim so we don't re-check every minute

        mentors = User.query.filter(User.role.in_(['mentor', 'admin'])).all()
        messages = []
        s_start = to_local_naive(build_session.start_time)
        subject = f"Absences for {build_session.title} on {s_start:%b} {s_start.day}"
        for mentor in mentors:
            if not mentor.email:
                continue
            body = _reminder_body(mentor.name or mentor.email, build_session, absentees)
            messages.append(_make_message(mentor.email, subject, body))

        try:
            sent = send_emails(messages)
        except Exception:
            app.logger.exception("Could not connect to SMTP server for session %s", build_session.id)
            sent = 0

        if messages and sent == 0:
            # Total failure: release the claim so the next check retries (until the session starts).
            db.session.delete(SessionReminder.query.filter_by(session_id=build_session.id).first())
            db.session.commit()
            app.logger.error("Absence reminder for session %s failed; will retry.", build_session.id)
        else:
            app.logger.info("Absence reminder for session %s sent to %d mentor(s).", build_session.id, sent)


def _reminder_loop():
    while True:
        try:
            with app.app_context():
                process_session_reminders()
        except Exception:
            app.logger.exception("Reminder check failed")
        time.sleep(REMINDER_CHECK_INTERVAL_SECONDS)


def start_reminder_scheduler():
    if not smtp_configured():
        app.logger.warning(
            "Mentor absence reminders are OFF: set SMTP_HOST, SMTP_USER and SMTP_PASSWORD in .env to enable them."
        )
        return
    threading.Thread(target=_reminder_loop, name="absence-reminders", daemon=True).start()
    app.logger.info("Mentor absence reminders ON (sent %s hours before each session).", REMINDER_HOURS_BEFORE)

# ==========================================
# PROTECTED MEDIA ROUTE
# ==========================================

@app.route('/photos/<filename>')
@login_required
def get_photo(filename):
    current_user = User.query.get(session['user_id'])
    
    # Locate user who owns this filename
    target_user = User.query.filter(User.photo_url.endswith(filename)).first()
    
    if not target_user:
        abort(404)

    if current_user.id != target_user.id and not current_user.is_mentor_or_admin:
        abort(403)

    return send_from_directory(app.config['UPLOAD_FOLDER'], filename)

# ==========================================
# AUTHENTICATION ROUTES
# ==========================================

@app.route('/')
def index():
    if 'user_id' in session:
        return redirect(url_for('dashboard'))
    return render_template('index.html')

@app.route('/login')
def login():
    redirect_uri = url_for('auth_callback', _external=True)
    return google.authorize_redirect(redirect_uri)

@app.route('/auth/callback')
def auth_callback():
    token = google.authorize_access_token()
    user_info = token.get('userinfo')
    
    if not user_info:
        user_info = google.get('userinfo').json()
        
    email = user_info.get('email', '').lower()

    admin_email = os.getenv("ADMIN_EMAIL", "").lower()
    user = User.query.filter_by(email=email).first()

    if not user:
        if admin_email and email == admin_email:
            user = User(email=email, name=user_info.get('name', 'Admin'), role='admin')
            db.session.add(user)
            db.session.commit()
        else:
            flash("Your email has not been provisioned by an administrator yet.", "danger")
            return redirect(url_for('index'))

    if admin_email and email == admin_email and user.role != 'admin':
        user.role = 'admin'
        db.session.commit()

    session['user_id'] = user.id
    session['user_role'] = user.role
    session['user_name'] = user.name or user.email
    flash(f"Welcome back, {user.name or user.email}!", "success")
    return redirect(url_for('dashboard'))

@app.route('/logout')
def logout():
    session.clear()
    flash("You have logged out.", "info")
    return redirect(url_for('index'))

# ==========================================
# USER & STUDENT ROUTES
# ==========================================

@app.route('/dashboard')
@login_required
def dashboard():
    user = User.query.get(session['user_id'])
    now_mountain = get_local_now()
    
    # Fetch all build sessions ordered by start time
    all_sessions = BuildSession.query.order_by(BuildSession.start_time.asc()).all()

    calendar_events = []
    upcoming_sessions = []

    for s in all_sessions:
        s_start = to_local_naive(s.start_time)
        s_end = to_local_naive(s.end_time)
        
        # Cutoff rule: Report absence allowed ONLY up to 5 hours before start_time
        absence_deadline = s_start - timedelta(hours=ABSENCE_CUTOFF_HOURS)
        is_locked = now_mountain >= absence_deadline

        if not is_locked:
            upcoming_sessions.append(s)

        calendar_events.append({
            'id': s.id,
            'title': s.title,
            'location': s.location,
            'start': s_start.strftime('%Y-%m-%dT%H:%M:%S'),
            'end': s_end.strftime('%Y-%m-%dT%H:%M:%S'),
            'is_past': is_locked  # Greys out/locks calendar event when cutoff is reached
        })
        
    logs = AttendanceLog.query.filter_by(user_id=user.id).order_by(AttendanceLog.check_in.desc()).all()
    open_logs = AttendanceLog.query.filter_by(user_id=user.id, check_out=None).order_by(AttendanceLog.check_in.desc()).all()
    total_hours = sum(log.duration_hours for log in logs)

    return render_template(
        'dashboard.html', 
        user=user, 
        upcoming_sessions=upcoming_sessions,
        calendar_events_json=json.dumps(calendar_events),
        logs=logs,
        open_logs=open_logs,
        total_hours=round(total_hours, 2),
        server_time_str=now_mountain.strftime('%Y-%m-%d %I:%M %p MST')
    )

@app.route('/attendance/checkout/<int:log_id>', methods=['POST'])
@login_required
def checkout_attendance(log_id):
    log = AttendanceLog.query.filter_by(
        id=log_id,
        user_id=session['user_id'],
        check_out=None
    ).first()

    if not log:
        flash("That attendance session is already closed or was not found.", "warning")
        return redirect(url_for('dashboard'))

    log.check_out = get_local_now()
    db.session.commit()
    flash(f"You signed out of {log.session.title}.", "success")
    return redirect(url_for('dashboard'))

@app.route('/absence/report', methods=['POST'])
@login_required
def report_absence():
    user_id = session['user_id']
    session_id = request.form.get('session_id')
    start_str = request.form.get('start_time')
    end_str = request.form.get('end_time')
    reason = request.form.get('reason')

    build_session = BuildSession.query.get_or_404(session_id)
    now_mountain = get_local_now()
    s_start = to_local_naive(build_session.start_time)

    # Server-side validation for 5-hour cutoff rule
    absence_deadline = s_start - timedelta(hours=ABSENCE_CUTOFF_HOURS)
    if now_mountain >= absence_deadline:
        flash(f"Absences must be reported at least {ABSENCE_CUTOFF_HOURS} hours prior to session start.", "danger")
        return redirect(url_for('dashboard'))

    start_time = datetime.strptime(start_str, '%Y-%m-%dT%H:%M') if start_str else build_session.start_time
    end_time = datetime.strptime(end_str, '%Y-%m-%dT%H:%M') if end_str else build_session.end_time

    notice = AbsenceNotice(
        user_id=user_id,
        session_id=build_session.id,
        start_time=to_local_naive(start_time),
        end_time=to_local_naive(end_time),
        reason=reason
    )
    db.session.add(notice)
    db.session.commit()
    flash("Absence report submitted successfully.", "success")
    return redirect(url_for('dashboard'))

# ==========================================
# MENTOR ROUTES
# ==========================================

@app.route('/mentor/sessions', methods=['GET', 'POST'])
@role_required('mentor', 'admin')
def mentor_sessions():
    if request.method == 'POST':
        title = request.form.get('title')
        location = request.form.get('location')
        start_str = request.form.get('start_time')
        end_str = request.form.get('end_time')

        start_time = datetime.strptime(start_str, '%Y-%m-%dT%H:%M')
        end_time = datetime.strptime(end_str, '%Y-%m-%dT%H:%M')

        new_session = BuildSession(
            title=title,
            location=location,
            start_time=to_local_naive(start_time),
            end_time=to_local_naive(end_time),
            created_by=session['user_id']
        )
        db.session.add(new_session)
        db.session.commit()
        flash("Build session created.", "success")
        return redirect(url_for('mentor_sessions'))

    sessions = BuildSession.query.order_by(BuildSession.start_time.desc()).all()
    return render_template('mentor_sessions.html', sessions=sessions)

@app.route('/mentor/sessions/<int:session_id>/edit', methods=['POST'])
@role_required('mentor', 'admin')
def mentor_edit_session(session_id):
    build_session = BuildSession.query.get_or_404(session_id)

    title = request.form.get('title', '').strip()
    location = request.form.get('location', '').strip()
    start_time = _parse_session_datetime(request.form.get('start_time'))
    end_time = _parse_session_datetime(request.form.get('end_time'))

    if not title or not location or not start_time or not end_time:
        flash("Title, location, start time and end time are all required.", "danger")
    elif end_time <= start_time:
        flash("End time must be after start time.", "danger")
    else:
        start_changed = build_session.start_time != start_time
        build_session.title = title
        build_session.location = location
        build_session.start_time = start_time
        build_session.end_time = end_time

        # If the session was moved, let the mentor reminder be sent again for the new time.
        if start_changed:
            SessionReminder.query.filter_by(session_id=build_session.id).delete()

        db.session.commit()
        flash(f"Updated \"{title}\".", "success")

    return redirect(url_for('mentor_sessions'))

@app.route('/mentor/sessions/<int:session_id>/delete', methods=['POST'])
@role_required('mentor', 'admin')
def mentor_delete_session(session_id):
    build_session = BuildSession.query.get_or_404(session_id)

    open_logs = AttendanceLog.query.filter_by(session_id=session_id, check_out=None).count()
    if open_logs:
        flash(f"Can't delete \"{build_session.title}\" while {open_logs} "
              f"{'person is' if open_logs == 1 else 'people are'} still signed in to it.", "warning")
        return redirect(url_for('mentor_sessions'))

    title = build_session.title

    # Absence reports for the session are removed along with it.
    AbsenceNotice.query.filter_by(session_id=session_id).delete()
    SessionReminder.query.filter_by(session_id=session_id).delete()

    # Hours people already earned are kept: detach those logs from the session
    # and leave a note so the history still says where they came from.
    for log in AttendanceLog.query.filter_by(session_id=session_id).all():
        log.session_id = None
        if not log.note:
            log.note = f"Deleted session: {title}"[:255]

    db.session.delete(build_session)
    db.session.commit()
    flash(f"Deleted \"{title}\".", "success")
    return redirect(url_for('mentor_sessions'))

@app.route('/mentor/invite', methods=['POST'])
@role_required('mentor', 'admin')
def mentor_invite_students():
    """Email every student a link to the portal and a short explanation of what it's for."""
    if not smtp_configured():
        flash("Email isn't set up yet. Add the SMTP settings to .env first.", "danger")
        return redirect(url_for('mentor_sessions'))

    students = User.query.filter_by(role='student').all()
    subject = "Attendance system for build sessions"
    messages = [
        _make_message(u.email, subject, _invite_body(u.name or u.email, u.email))
        for u in students if u.email
    ]

    if not messages:
        flash("There are no students to invite yet.", "warning")
        return redirect(url_for('mentor_sessions'))

    try:
        sent = send_emails(messages)
    except Exception:
        app.logger.exception("Could not connect to SMTP server to send invitations")
        flash("Couldn't connect to the email server. Check the SMTP settings in .env.", "danger")
        return redirect(url_for('mentor_sessions'))

    if sent == len(messages):
        flash(f"Invitation sent to {sent} student{'s' if sent != 1 else ''}.", "success")
    else:
        flash(f"Invitation sent to {sent} of {len(messages)} students. Check the server log for the failures.", "warning")
    return redirect(url_for('mentor_sessions'))

# Accepted formats for start_time / end_time columns in an imported CSV.
_SESSION_DT_FORMATS = [
    '%Y-%m-%dT%H:%M',
    '%Y-%m-%d %H:%M',
    '%Y-%m-%d %H:%M:%S',
    '%m/%d/%Y %H:%M',
    '%m/%d/%Y %I:%M %p',
]

def _parse_session_datetime(value):
    value = (value or '').strip()
    for fmt in _SESSION_DT_FORMATS:
        try:
            return datetime.strptime(value, fmt)
        except ValueError:
            continue
    return None

@app.route('/mentor/sessions/import', methods=['POST'])
@role_required('mentor', 'admin')
def mentor_sessions_import():
    """Bulk-create build sessions from an uploaded CSV.

    Expected columns (header row required, case-insensitive):
      title, location, start_time, end_time
    Datetime values may be formatted like 2026-03-14T18:00, 2026-03-14 18:00,
    or 03/14/2026 6:00 PM.
    """
    file = request.files.get('csv_file')

    if not file or file.filename == '':
        flash("Choose a CSV file to import first.", "warning")
        return redirect(url_for('mentor_sessions'))

    if not file.filename.lower().endswith('.csv'):
        flash("That doesn't look like a CSV file.", "danger")
        return redirect(url_for('mentor_sessions'))

    try:
        raw = file.read().decode('utf-8-sig')
    except UnicodeDecodeError:
        flash("Couldn't read that file as text. Please export it as a UTF-8 CSV.", "danger")
        return redirect(url_for('mentor_sessions'))

    reader = csv.DictReader(io.StringIO(raw))

    if not reader.fieldnames:
        flash("The CSV file appears to be empty.", "danger")
        return redirect(url_for('mentor_sessions'))

    # Normalize header names so casing/whitespace differences don't break matching.
    field_map = {name.strip().lower(): name for name in reader.fieldnames}
    required = ['title', 'location', 'start_time', 'end_time']
    missing = [col for col in required if col not in field_map]
    if missing:
        flash(f"CSV is missing required column(s): {', '.join(missing)}.", "danger")
        return redirect(url_for('mentor_sessions'))

    imported = 0
    errors = []

    for row_num, row in enumerate(reader, start=2):  # row 1 is the header
        title = (row.get(field_map['title']) or '').strip()
        location = (row.get(field_map['location']) or '').strip()
        start_raw = row.get(field_map['start_time'])
        end_raw = row.get(field_map['end_time'])

        if not title or not location or not start_raw or not end_raw:
            errors.append(f"Row {row_num}: missing a required value.")
            continue

        start_time = _parse_session_datetime(start_raw)
        end_time = _parse_session_datetime(end_raw)

        if not start_time or not end_time:
            errors.append(f"Row {row_num}: couldn't parse start/end time.")
            continue

        if end_time <= start_time:
            errors.append(f"Row {row_num}: end time must be after start time.")
            continue

        new_session = BuildSession(
            title=title,
            location=location,
            start_time=to_local_naive(start_time),
            end_time=to_local_naive(end_time),
            created_by=session['user_id']
        )
        db.session.add(new_session)
        imported += 1

    if imported:
        db.session.commit()
        flash(f"Imported {imported} build session{'s' if imported != 1 else ''} from CSV.", "success")

    if errors:
        preview = "; ".join(errors[:5])
        more = f" (+{len(errors) - 5} more)" if len(errors) > 5 else ""
        flash(f"Skipped {len(errors)} row(s): {preview}{more}", "warning")

    return redirect(url_for('mentor_sessions'))

@app.route('/mentor/absences')
@role_required('mentor', 'admin')
def mentor_absences():
    sessions = BuildSession.query.order_by(BuildSession.start_time.desc()).all()
    selected_id = request.args.get('session_id', type=int)
    
    selected_session = None
    absences = []
    
    if selected_id:
        selected_session = BuildSession.query.get(selected_id)
        if selected_session:
            absences = AbsenceNotice.query.filter_by(session_id=selected_id).all()
    elif sessions:
        selected_session = sessions[0]
        absences = AbsenceNotice.query.filter_by(session_id=selected_session.id).all()

    return render_template(
        'mentor_absences.html', 
        sessions=sessions, 
        selected_session=selected_session, 
        absences=absences
    )

@app.route('/mentor/monitor')
@role_required('mentor', 'admin')
def mentor_monitor():
    now_mountain = get_local_now()
    current_session = BuildSession.query.filter(
        BuildSession.start_time <= now_mountain,
        BuildSession.end_time >= now_mountain
    ).order_by(BuildSession.start_time.desc()).first()
    signed_in_logs = AttendanceLog.query.join(User).filter(
        AttendanceLog.check_out.is_(None),
        User.role.in_(['student', 'mentor', 'admin'])
    ).order_by(AttendanceLog.check_in.asc()).all()

    return render_template(
        'mentor_monitor.html',
        current_session=current_session,
        signed_in_logs=signed_in_logs,
        now_mountain=now_mountain
    )

@app.route('/mentor/students')
@role_required('mentor', 'admin')
def mentor_students():
    students = User.query.all()
    selected_id = request.args.get('user_id', type=int)
    
    selected_user = None
    user_logs = []
    open_logs = []
    user_absences = []
    total_hours = 0.0

    if selected_id:
        selected_user = User.query.get(selected_id)
        if selected_user:
            user_logs = AttendanceLog.query.filter_by(user_id=selected_id).order_by(AttendanceLog.check_in.desc()).all()
            user_absences = AbsenceNotice.query.filter_by(user_id=selected_id).all()
            total_hours = sum(log.duration_hours for log in user_logs)

            open_logs = [log for log in user_logs if log.check_out is None]

    return render_template(
        'mentor_students.html', 
        students=students, 
        selected_user=selected_user, 
        logs=user_logs, 
        open_logs=open_logs,
        absences=user_absences, 
        total_hours=round(total_hours, 2)
    )

@app.route('/mentor/students/checkout/<int:log_id>', methods=['POST'])
@role_required('mentor', 'admin')
def mentor_checkout_attendance(log_id):
    log = AttendanceLog.query.filter_by(id=log_id, check_out=None).first()
    selected_id = request.form.get('user_id', type=int)

    if not log:
        flash("That attendance session is already closed or was not found.", "warning")
    else:
        log.check_out = get_local_now()
        db.session.commit()
        selected_id = log.user_id
        flash(f"Closed {log.user.name or log.user.email}'s session for {log.session.title}.", "success")

    return redirect(url_for('mentor_students', user_id=selected_id))

@app.route('/mentor/students/wipe_checkout/<int:log_id>', methods=['POST'])
@role_required('mentor', 'admin')
def mentor_wipe_checkout(log_id):
    """Sign a currently-open attendance session out, but discard it entirely
    so no hours are credited for that session."""
    log = AttendanceLog.query.filter_by(id=log_id, check_out=None).first()
    selected_id = request.form.get('user_id', type=int)

    if not log:
        flash("That attendance session is already closed or was not found.", "warning")
    else:
        selected_id = log.user_id
        name = log.user.name or log.user.email
        session_title = log.session.title if log.session else "their open session"
        db.session.delete(log)
        db.session.commit()
        flash(f"Signed {name} out of {session_title} with no hours credited.", "success")

    return redirect(url_for('mentor_students', user_id=selected_id))

@app.route('/mentor/students/log/<int:log_id>/delete', methods=['POST'])
@role_required('mentor', 'admin')
def mentor_delete_log(log_id):
    """Delete an attendance log entry entirely (real or manual), adjusting the
    student's total hours."""
    log = AttendanceLog.query.get(log_id)
    selected_id = request.form.get('user_id', type=int)

    if not log:
        flash("That attendance record was not found.", "warning")
    else:
        selected_id = log.user_id
        name = log.user.name or log.user.email
        hours = log.duration_hours
        db.session.delete(log)
        db.session.commit()
        flash(f"Deleted a {hours} hr record for {name}.", "success")

    return redirect(url_for('mentor_students', user_id=selected_id))

@app.route('/mentor/students/adjust_hours', methods=['POST'])
@role_required('mentor', 'admin')
def mentor_adjust_hours():
    """Manually add or remove hours from a student's total, independent of any
    real check-in/check-out. Recorded as a manual AttendanceLog row so it shows
    up in the log history and can itself be deleted later."""
    user_id = request.form.get('user_id', type=int)
    action = request.form.get('adjust_action')  # 'add' or 'remove'
    hours = request.form.get('hours', type=float)
    reason = request.form.get('reason', '').strip()

    user = User.query.get(user_id)

    if not user:
        flash("Student not found.", "danger")
        return redirect(url_for('mentor_students'))

    if not hours or hours <= 0:
        flash("Enter a positive number of hours to add or remove.", "warning")
        return redirect(url_for('mentor_students', user_id=user_id))

    signed_hours = hours if action == 'add' else -hours
    now = get_local_now()

    note = reason if reason else ("Manual addition" if action == 'add' else "Manual deduction")

    adjustment = AttendanceLog(
        user_id=user.id,
        session_id=None,
        check_in=now,
        check_out=now + timedelta(hours=signed_hours),
        note=note,
        is_manual=True
    )
    db.session.add(adjustment)
    db.session.commit()

    verb = "Added" if action == 'add' else "Removed"
    flash(f"{verb} {hours} hrs {'to' if action == 'add' else 'from'} {user.name or user.email}'s total.", "success")
    return redirect(url_for('mentor_students', user_id=user_id))

# ==========================================
# ADMIN ROUTES
# ==========================================

@app.route('/admin/users', methods=['GET', 'POST'])
@role_required('admin')
def admin_users():
    if request.method == 'POST':
        action = request.form.get('action')
        
        if action == 'provision':
            email = request.form.get('email', '').lower()
            barcode = request.form.get('barcode')
            name = request.form.get('name')
            role = request.form.get('role', 'student')
            
            if User.query.filter_by(email=email).first():
                flash("User with this email already exists.", "danger")
            else:
                user = User(email=email, barcode=barcode, name=name, role=role)
                db.session.add(user)
                db.session.commit()
                flash(f"Provisioned user {email}.", "success")
                
        elif action == 'update_role':
            user_id = request.form.get('user_id')
            new_role = request.form.get('role')
            user = User.query.get(user_id)
            if user:
                user.role = new_role
                db.session.commit()
                flash(f"Updated role for {user.email} to {new_role}.", "success")
                
        elif action == 'edit_user':
            user_id = request.form.get('user_id')
            user = User.query.get(user_id)
            new_email = request.form.get('email', '').strip().lower()
            new_name = request.form.get('name', '').strip()
            new_barcode = request.form.get('barcode', '').strip() or None

            if not user:
                flash("User not found.", "danger")
            elif not new_email:
                flash("Email cannot be blank.", "danger")
            elif User.query.filter(User.email == new_email, User.id != user.id).first():
                flash("Another user already has that email.", "danger")
            elif new_barcode and User.query.filter(User.barcode == new_barcode, User.id != user.id).first():
                flash("Another user already has that barcode.", "danger")
            else:
                user.email = new_email
                user.name = new_name or None
                user.barcode = new_barcode
                db.session.commit()
                flash(f"Updated details for {user.email}.", "success")

        elif action == 'upload_photo':
            user_id = request.form.get('user_id')
            user = User.query.get(user_id)
            file = request.files.get('photo')
            if user and file:
                filename = secure_filename(f"user_{user.id}_{file.filename}")
                filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
                file.save(filepath)
                user.photo_url = f"photos/{filename}"
                db.session.commit()
                flash(f"Uploaded photo for {user.email}.", "success")

        return redirect(url_for('admin_users'))

    users = User.query.all()
    return render_template('admin_users.html', users=users)

@app.route('/admin/logs')
@role_required('admin')
def admin_logs():
    """A searchable, paginated log of every sign-in/sign-out event."""
    q = request.args.get('q', '').strip()
    session_id = request.args.get('session_id', type=int)
    role_filter = request.args.get('role', '').strip()
    page = request.args.get('page', 1, type=int)
    per_page = 50

    query = AttendanceLog.query.join(User)

    if q:
        like = f"%{q}%"
        query = query.filter(
            db.or_(
                User.name.ilike(like),
                User.email.ilike(like),
                User.barcode.ilike(like)
            )
        )

    if session_id:
        query = query.filter(AttendanceLog.session_id == session_id)

    if role_filter in ('student', 'mentor', 'admin'):
        query = query.filter(User.role == role_filter)

    query = query.order_by(AttendanceLog.check_in.desc())

    total = query.count()
    total_pages = max(1, (total + per_page - 1) // per_page)
    page = max(1, min(page, total_pages))
    logs = query.offset((page - 1) * per_page).limit(per_page).all()

    sessions = BuildSession.query.order_by(BuildSession.start_time.desc()).all()

    return render_template(
        'admin_logs.html',
        logs=logs,
        sessions=sessions,
        q=q,
        session_id=session_id,
        role_filter=role_filter,
        page=page,
        total_pages=total_pages,
        total=total
    )

# ==========================================
# KIOSK ENGINE (BARCODE CHECK-IN/OUT)
# ==========================================

@app.route('/kiosk')
def kiosk_page():
    return render_template('kiosk.html')

@app.route('/kiosk/scan', methods=['POST'])
def kiosk_scan():
    kiosk_pass = request.json.get('kiosk_password')
    expected_pass = os.getenv("KIOSK_PASSWORD", "shop_kiosk_passcode_123")
    
    if kiosk_pass != expected_pass:
        return jsonify({"status": "error", "message": "Invalid Kiosk Password"}), 401

    barcode = request.json.get('barcode')
    user = User.query.filter_by(barcode=barcode).first()
    if not user:
        return jsonify({"status": "error", "message": "Barcode Unrecognized"}), 404

    now = get_local_now()
    
    open_log = AttendanceLog.query.filter_by(user_id=user.id, check_out=None).order_by(AttendanceLog.check_in.desc()).first()

    if open_log:
        open_log.check_out = now
        db.session.commit()

        if user.is_mentor_or_admin:
            other_active_mentors = AttendanceLog.query.join(User).filter(
                AttendanceLog.session_id == open_log.session_id,
                AttendanceLog.check_out == None,
                User.role.in_(['mentor', 'admin']),
                User.id != user.id
            ).count()

            if other_active_mentors == 0:
                unclaimed_student_logs = AttendanceLog.query.join(User).filter(
                    AttendanceLog.session_id == open_log.session_id,
                    AttendanceLog.check_out == None,
                    User.role == 'student'
                ).all()

                for unclosed_log in unclaimed_student_logs:
                    db.session.delete(unclosed_log)
                
                db.session.commit()

        return jsonify({
            "status": "success", 
            "action": "CHECK_OUT",
            "message": f"User ({barcode}) signed out!"
        })
    else:
        # A session is a candidate for check-in if it's currently running, OR it starts
        # within the early-checkin buffer window (students still need a mentor present
        # to use the buffer window; mentors/admins can always use it).
        candidate_session = BuildSession.query.filter(
            BuildSession.start_time <= now + timedelta(minutes=EARLY_CHECKIN_BUFFER_MINUTES),
            BuildSession.end_time >= now
        ).order_by(BuildSession.start_time.asc()).first()

        if not candidate_session:
            return jsonify({"status": "error", "message": "No Active Build Session Right Now"}), 400

        in_buffer = now < candidate_session.start_time

        if in_buffer and not user.is_mentor_or_admin:
            mentor_present = AttendanceLog.query.join(User).filter(
                AttendanceLog.session_id == candidate_session.id,
                AttendanceLog.check_out.is_(None),
                User.role.in_(['mentor', 'admin'])
            ).first() is not None

            if not mentor_present:
                minutes_until = max(1, int((candidate_session.start_time - now).total_seconds() // 60) + 1)
                return jsonify({
                    "status": "error",
                    "message": f"{candidate_session.title} starts in {minutes_until} min. Waiting for a mentor to sign in first."
                }), 400

        new_log = AttendanceLog(user_id=user.id, session_id=candidate_session.id, check_in=now)
        db.session.add(new_log)
        db.session.commit()

        message = f"User ({barcode}) signed in!"
        if in_buffer:
            message = f"User ({barcode}) signed in early — {candidate_session.title} starts soon!"

        return jsonify({
            "status": "success", 
            "action": "CHECK_IN",
            "message": message
        })

if __name__ == '__main__':
    with app.app_context():
        db.create_all()

    DEBUG_MODE = True
    # In debug mode Flask re-launches this script in a child process (the reloader);
    # only start the reminder thread in the process that actually serves requests.
    if not DEBUG_MODE or os.environ.get("WERKZEUG_RUN_MAIN") == "true":
        start_reminder_scheduler()

    app.run(host='0.0.0.0', port=5000, debug=DEBUG_MODE)